// SPDX-FileCopyrightText: 2026 The Cubepals Authors
//
// SPDX-License-Identifier: AGPL-3.0-only

import createClient, { type ClientOptions } from 'openapi-fetch'
import type { components, paths } from './generated/boat.ts'

/**
 * Boat's public API, typed from the OpenAPI spec Boat publishes at
 * https://docs.boat.dev/openapi/boat-v1.yaml (fetched and generated by tools/openapi). Only
 * `infra/boat/` sees these types; the rest of Blockly sees `MinecraftRuntime`.
 */
export type BoatClient = ReturnType<typeof createClient<paths>>
type BoatSchemas = components['schemas']
export type Sandbox = BoatSchemas['Sandbox']

const BOAT_API = 'https://boat.dev/api/v1'

export class BoatApiError extends Error {
  readonly status: number
  /** Boat's own name for what went wrong (`rate_limited`, `boat_starting`…), where it gave one. */
  readonly code: string | null

  constructor(status: number, what: string, detail: unknown) {
    const code = codeOf(detail)
    super(`Boat: ${what} failed with ${status}${code ? ` ${code}` : ''}${messageOf(detail)}`)
    this.name = 'BoatApiError'
    this.status = status
    this.code = code
  }
}

type Result<T> = { data?: T; error?: unknown; response: Response }

export function must<T>(result: Result<T>, what: string): T {
  if (!result.response.ok) throw new BoatApiError(result.response.status, what, result.error)
  return result.data as T
}

function codeOf(detail: unknown): string | null {
  if (typeof detail !== 'object' || detail === null) return null
  const code = (detail as { code?: unknown }).code
  return typeof code === 'string' ? code : null
}

function messageOf(detail: unknown): string {
  if (typeof detail !== 'object' || detail === null) return ''
  const message = (detail as { message?: unknown }).message
  return typeof message === 'string' ? `: ${message.slice(0, 200)}` : ''
}

type Send = NonNullable<ClientOptions['fetch']>
type BoatRequest = Parameters<Send>[0]

export interface BoatClientOptions {
  baseUrl?: string
  /** Where requests go. Tests pass an in-memory Boat API. */
  fetch?: Send
}

export function boatClient(token: string, options: BoatClientOptions = {}): BoatClient {
  const send: Send = options.fetch ?? ((request) => fetch(request))
  return createClient<paths>({
    baseUrl: options.baseUrl ?? BOAT_API,
    headers: { Authorization: `Bearer ${token}` },
    fetch: (request) => retried(request, send),
  })
}

/**
 * Creates, forks and resumes are machine starts: their 429 is the start limit, which the caller
 * reads and decides about (starts.ts), so it is never waited out here.
 */
const STARTS = /\/sandboxes(\/[^/]+\/(resume|fork))?$/

/**
 * A read or a delete is safe to repeat, so a 502–504 or a dropped connection is tried again; a
 * 429 that isn't a start waits out Retry-After. A command is never repeated here: Boat says it may
 * already be running (`boat_direct_failed`), and the adapter's own scripts decide.
 */
async function retried(request: BoatRequest, send: Send): Promise<Response> {
  const path = new URL(request.url).pathname
  const repeatable = request.method === 'GET' || request.method === 'DELETE'
  const start = request.method === 'POST' && STARTS.test(path)
  for (let attempt = 0; ; attempt++) {
    // Bun's and Node's type packages each declare Request; clone() returns the other one's.
    const response = await send(request.clone() as BoatRequest).catch((error: unknown) => {
      if (!repeatable || attempt >= 4) throw error
      return null
    })
    if (response === null) {
      await sleep(backoffMs(attempt))
      continue
    }
    const again =
      (response.status === 429 && !start) || (repeatable && response.status >= 502 && response.status <= 504)
    if (!again || attempt >= 4) return response
    await response.body?.cancel()
    const seconds = Number(response.headers.get('retry-after'))
    await sleep(Number.isFinite(seconds) && seconds > 0 ? seconds * 1000 : backoffMs(attempt))
  }
}

const backoffMs = (attempt: number) => Math.min(8000, 500 * 2 ** attempt) + Math.random() * 250

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms))
