// SPDX-FileCopyrightText: 2026 The Cubepals Authors
//
// SPDX-License-Identifier: AGPL-3.0-only

/**
 * Every Hetzner offering in the catalog.
 * Its cloud VM for one server, its large cloud VMs and its dedicated servers are three arrays,
 * because each sits in a different place in `CATALOG`.
 */
import { CHECKED, type Offering, passmark } from './offering.ts'

const HETZNER_DEDICATED = {
  provider: 'Hetzner',
  modelClass: 'C',
  regions: 'FSN1 Falkenstein, HEL1 Helsinki',
  regionGroup: 'EU',
  currency: 'EUR',
  minTerm: 'none; cancellation immediate',
  billing: 'hourly up to a monthly cap (about 624 h)',
  billedWhenOff: true,
  dedicatedCpu: true,
  raid1: true,
  bandwidth: 'unlimited on a 1 Gbit/s port',
  egressOveragePerTb: 0,
  ipv4Monthly: 1.7,
  ddos: 'automatic L3/L4 filtering (Arbor/Juniper; Nokia Deepfield since March 2026), nothing Minecraft-aware',
  gameAwareDdos: false,
  checked: CHECKED,
  sourceNote: 'hetzner.md (§2, SKU data)',
} as const
const HETZNER_AX_SOURCE =
  'https://www.hetzner.com/dedicated-rootserver/matrix-ax ; https://docs.hetzner.com/general/infrastructure-and-availability/price-adjustment/'

export const HETZNER_VMS: readonly Offering[] = [
  {
    id: 'hetzner-ccx13',
    provider: 'Hetzner',
    product: 'Cloud CCX General Purpose (dedicated vCPU)',
    sku: 'CCX13',
    modelClass: 'A',
    regions: 'FSN1, NBG1, HEL1 (US ASH1/HIL1 €43.49)',
    regionGroup: 'EU',
    currency: 'EUR',
    monthlyPrice: 42.99,
    hourlyPrice: 0.0689,
    setupFee: 0,
    minTerm: 'none',
    billing: 'hourly, rounded up to whole hours, capped at the monthly price (~624 h)',
    billedWhenOff: true,
    ramGb: 8,
    cores: null,
    threads: 2,
    dedicatedCpu: true,
    cpuModel: 'AMD EPYC Milan or Genoa (not guaranteed which)',
    st: {
      passmark: null,
      index: [49, 61],
      tag: '[Independent]',
      basis: 'Kechagias 2026 tested CCX13 as Milan; varies by data centre (cpu-performance.md §2, §6)',
    },
    localDiskGb: 80,
    disks: '80 GB local NVMe',
    raid1: false,
    bandwidth: '20 TB/month egress (EU); 1 TB in the US',
    egressOveragePerTb: 1,
    ipv4Monthly: 0.5,
    storageWhileOffGbMonth: 0.0143,
    ddos: 'automatic L3/L4 filtering, nothing Minecraft-aware',
    gameAwareDdos: false,
    stock: 'orderable',
    inStock: true,
    checked: CHECKED,
    sourceNote: 'hetzner.md (§1, SKU data)',
    source:
      'https://www.hetzner.com/cloud/general-purpose ; https://docs.hetzner.com/general/infrastructure-and-availability/price-adjustment/',
    notes:
      '€15.99 before 15 Jun 2026 (+169%). Powered-off servers keep billing; deleting and keeping a snapshot costs €0.0143/GB-month. ' +
      'Default limit 8 dedicated-vCPU servers per project.',
  },
]

export const HETZNER_LARGE_VMS: readonly Offering[] = [
  {
    id: 'hetzner-ccx33',
    provider: 'Hetzner',
    product: 'Cloud CCX General Purpose (dedicated vCPU)',
    sku: 'CCX33',
    modelClass: 'B',
    regions: 'FSN1, NBG1, HEL1 (US €140.99)',
    regionGroup: 'EU',
    currency: 'EUR',
    monthlyPrice: 138.49,
    hourlyPrice: 0.2219,
    setupFee: 0,
    minTerm: 'none',
    billing: 'hourly, rounded up, capped at the monthly price',
    billedWhenOff: true,
    ramGb: 32,
    cores: null,
    threads: 8,
    dedicatedCpu: true,
    cpuModel: 'AMD EPYC Milan or Genoa (not guaranteed which)',
    st: {
      passmark: null,
      index: [49, 61],
      tag: '[Independent]',
      basis: 'as CCX13 (cpu-performance.md §6)',
    },
    localDiskGb: 240,
    disks: '240 GB local NVMe',
    raid1: false,
    bandwidth: '30 TB/month egress (EU)',
    egressOveragePerTb: 1,
    ipv4Monthly: 0.5,
    ddos: 'automatic L3/L4 filtering, nothing Minecraft-aware',
    gameAwareDdos: false,
    stock: 'orderable',
    inStock: true,
    checked: CHECKED,
    sourceNote: 'hetzner.md (§1, SKU data)',
    source: 'https://www.hetzner.com/cloud/general-purpose',
    notes: '€62.49 before 15 Jun 2026. 1 vCPU = 1 hardware thread, so 8 vCPU ≈ 4 cores.',
  },
  {
    id: 'hetzner-ccx63',
    provider: 'Hetzner',
    product: 'Cloud CCX General Purpose (dedicated vCPU)',
    sku: 'CCX63',
    modelClass: 'B',
    regions: 'FSN1, NBG1, HEL1 (US €859.99)',
    regionGroup: 'EU',
    currency: 'EUR',
    monthlyPrice: 853.49,
    hourlyPrice: 1.3678,
    setupFee: 0,
    minTerm: 'none',
    billing: 'hourly, rounded up, capped at the monthly price',
    billedWhenOff: true,
    ramGb: 192,
    cores: null,
    threads: 48,
    dedicatedCpu: true,
    cpuModel: 'AMD EPYC Milan or Genoa (not guaranteed which)',
    st: {
      passmark: null,
      index: [49, 61],
      tag: '[Independent]',
      basis: 'as CCX13 (cpu-performance.md §6)',
    },
    localDiskGb: 960,
    disks: '960 GB local NVMe',
    raid1: false,
    bandwidth: '60 TB/month egress (EU)',
    egressOveragePerTb: 1,
    ipv4Monthly: 0.5,
    ddos: 'automatic L3/L4 filtering, nothing Minecraft-aware',
    gameAwareDdos: false,
    stock: 'orderable',
    inStock: true,
    checked: CHECKED,
    sourceNote: 'hetzner.md (§1, SKU data)',
    source: 'https://www.hetzner.com/cloud/general-purpose',
    notes:
      '€374.49 before 15 Jun 2026. Conflict: the official table lists the US CCX63 at €853.49, live data €859.99 (hetzner.md §1).',
  },
]

export const HETZNER_SERVERS: readonly Offering[] = [
  {
    ...HETZNER_DEDICATED,
    id: 'hetzner-ax42-1',
    product: 'AX42-1',
    sku: 'AX42-1',
    monthlyPrice: 97.3,
    hourlyPrice: 0.1559,
    setupFee: 49,
    ramGb: 64,
    cores: 8,
    threads: 16,
    cpuModel: 'AMD Ryzen 7 PRO 8700GE (Zen 4, 35 W)',
    st: passmark(3859, '169 samples; a 35 W part, sustained all-core clocks unknown'),
    localDiskGb: 1024,
    disks: '2× 512 GB NVMe',
    stock: 'listed in FSN1 and HEL1 availability data',
    inStock: true,
    source: HETZNER_AX_SOURCE,
    notes: 'USD account: $117.10 + $59 setup. 64 GB DDR5 non-ECC.',
  },
  {
    ...HETZNER_DEDICATED,
    id: 'hetzner-ax42-1-ltd',
    product: 'AX42-1-LTD (limited stock)',
    sku: 'AX42-1-LTD',
    monthlyPrice: 77.3,
    hourlyPrice: 0.1239,
    setupFee: 39,
    ramGb: 64,
    cores: 8,
    threads: 16,
    cpuModel: 'AMD Ryzen 7 PRO 8700GE (Zen 4, 35 W)',
    st: passmark(3859, '169 samples'),
    localDiskGb: 1024,
    disks: '2× 512 GB NVMe',
    stock:
      'LTD tiers appear only with cheaper hardware; not listed in the site availability data on 2026-10-01',
    inStock: null,
    source: `${HETZNER_AX_SOURCE} ; https://website-price-api.hetzner.com/api/v1/products/ROBOT_1720`,
    notes: 'Conflict: USD price $77.30 (official table) vs $87.10 (price API).',
  },
  {
    ...HETZNER_DEDICATED,
    id: 'hetzner-ax102-1',
    product: 'AX102-1',
    sku: 'AX102-1',
    monthlyPrice: 257.3,
    hourlyPrice: 0.4123,
    setupFee: 129,
    ramGb: 128,
    cores: 16,
    threads: 32,
    cpuModel: 'AMD Ryzen 9 7950X3D (Zen 4, 3D V-Cache)',
    st: passmark(4144, '6,678 samples'),
    localDiskGb: 3840,
    disks: '2× 1.92 TB NVMe DC',
    stock: 'listed in FSN1 and HEL1 availability data',
    inStock: true,
    source: HETZNER_AX_SOURCE,
    notes: 'USD $302.10 + $149. The setup fee is about two weeks of rent.',
  },
  {
    ...HETZNER_DEDICATED,
    id: 'hetzner-ax102-1-ltd',
    product: 'AX102-1-LTD (limited stock)',
    sku: 'AX102-1-LTD',
    monthlyPrice: 157.3,
    hourlyPrice: 0.2521,
    setupFee: 39,
    ramGb: 128,
    cores: 16,
    threads: 32,
    cpuModel: 'AMD Ryzen 9 7950X3D (Zen 4, 3D V-Cache)',
    st: passmark(4144, '6,678 samples'),
    localDiskGb: 3840,
    disks: '2× 1.92 TB NVMe DC',
    stock: 'not listed in the site availability data on 2026-10-01; may be out of stock',
    inStock: null,
    source: `${HETZNER_AX_SOURCE} ; https://website-price-api.hetzner.com/api/v1/products/ROBOT_1723`,
    notes: 'USD $187.10 + $39.',
  },
  {
    ...HETZNER_DEDICATED,
    id: 'hetzner-ex63-1',
    product: 'EX63-1',
    sku: 'EX63-1',
    monthlyPrice: 147.3,
    hourlyPrice: 0.2361,
    setupFee: 74,
    ramGb: 64,
    cores: 20,
    fastCores: 8,
    threads: 20,
    cpuModel: 'Intel Core Ultra 7 265 (Arrow Lake, 8P + 12E, no SMT)',
    st: passmark(4694, '2,137 samples; only the 8 P-cores reach it'),
    localDiskGb: 2000,
    disks: '2× 1 TB NVMe',
    stock: 'listed in FSN1 and HEL1 availability data',
    inStock: true,
    source:
      'https://www.hetzner.com/dedicated-rootserver/matrix-ex ; https://docs.hetzner.com/general/infrastructure-and-availability/price-adjustment/',
    notes:
      'USD $172.10 + $84. The conservative rule counts only the 8 P-cores; the normal rule counts all 20 threads.',
  },
  {
    ...HETZNER_DEDICATED,
    id: 'hetzner-auction-7700',
    product: 'Server Auction listing (refurbished)',
    sku: 'SB-3075420',
    regions: 'FSN1-DC6',
    monthlyPrice: 108,
    hourlyPrice: 0.1731,
    setupFee: 0,
    minTerm: 'none; cancellation immediate',
    billing: 'hourly up to the monthly price; the listing price falls until bought, then is fixed',
    ramGb: 64,
    cores: 8,
    threads: 16,
    cpuModel: 'AMD Ryzen 7 7700 (Zen 4)',
    st: passmark(4050, '6,930 samples'),
    localDiskGb: 2000,
    disks: '2× 1 TB NVMe',
    stock: 'one listing on 2026-10-01; 8 Ryzen 7 7700 listings at €108–334',
    inStock: true,
    source: 'https://www.hetzner.com/sb ; https://www.hetzner.com/_resources/app/data/app/live_data_sb.json',
    notes: 'A snapshot of one Dutch-auction listing (non-ECC RAM); no setup fee. USD account $120.',
  },
]
