// SPDX-FileCopyrightText: 2026 The Cubepals Authors
//
// SPDX-License-Identifier: AGPL-3.0-only

/**
 * OVHcloud's dedicated servers as catalog entries.
 * The EU company and OVHcloud US are two arrays, because each sits in a different place in `CATALOG`.
 */
import { CHECKED, type Offering, passmark } from './offering.ts'

const OVH_EU_ECO = 'https://eu.api.ovh.com/v1/order/catalog/public/eco?ovhSubsidiary=FR'
const OVH_EU_BM = 'https://eu.api.ovh.com/v1/order/catalog/public/baremetalServers?ovhSubsidiary=FR'
const OVH_US_ECO = 'https://api.us.ovhcloud.com/v1/order/catalog/public/eco?ovhSubsidiary=US'
const OVH_US_BM = 'https://api.us.ovhcloud.com/v1/order/catalog/public/baremetalServers?ovhSubsidiary=US'
const OVH_DEDICATED = {
  provider: 'OVHcloud',
  modelClass: 'C',
  minTerm: '1 month, renews monthly; 12/24-month upfront waives the setup fee and takes 5% off',
  billing: 'monthly, prepaid; setup fee = one month on no-commitment orders',
  billedWhenOff: true,
  dedicatedCpu: true,
  raid1: true,
  egressOveragePerTb: 0,
  ipv4Monthly: 0,
  checked: CHECKED,
  sourceNote: 'ovhcloud.md (§1, SKU data); regions.md (§1 stock)',
} as const
const OVH_RAM_GAME = [
  { ramGb: 128, extraMonthly: 91 },
  { ramGb: 192, extraMonthly: 178 },
  { ramGb: 256, extraMonthly: 254 },
] as const

export const OVH_EU_SERVERS: readonly Offering[] = [
  {
    ...OVH_DEDICATED,
    id: 'ovh-rise-game-1',
    product: 'RISE-GAME-1 (Eco game server)',
    sku: '24risegame012',
    regions: 'fra, gra, lon, sbg, waw, bhs',
    regionGroup: 'EU',
    currency: 'EUR',
    monthlyPrice: 64.99,
    hourlyPrice: null,
    setupFee: 64.99,
    ramGb: 32,
    ramOptions: [{ ramGb: 64, extraMonthly: 16 }],
    cores: 6,
    threads: 12,
    cpuModel: 'AMD Ryzen 5 5600X (Zen 3), 3.7/4.6 GHz',
    st: passmark(3366, '35,885 samples'),
    localDiskGb: 1024,
    disks: '2× 512 GB NVMe, software RAID',
    bandwidth: '1 Gbps unmetered, guaranteed; no vRack',
    ddos: 'Game DDoS Protection (Minecraft Java/Query profiles, 30 rules per IP)',
    gameAwareDdos: true,
    stock: 'fra, gra, lon, sbg, waw, bhs: 1H',
    inStock: true,
    source: `${OVH_EU_ECO} ; https://eco.ovhcloud.com/en-ie/rise/`,
    notes: '12-month upfront €740.89 (€61.74/month, no setup fee). Zen 3.',
  },
  {
    ...OVH_DEDICATED,
    id: 'ovh-rise-s',
    product: 'RISE-S (Rise, 2025 Zen 5)',
    sku: '25rises01-v2',
    regions: 'rbx, gra, sbg, waw, fra, bhs',
    regionGroup: 'EU',
    currency: 'EUR',
    monthlyPrice: 64.99,
    hourlyPrice: null,
    setupFee: 64.99,
    ramGb: 64,
    cores: 8,
    threads: 16,
    cpuModel: 'AMD Ryzen 7 9700X (Zen 5), 3.8/5.5 GHz',
    st: passmark(4642, '9,933 samples'),
    localDiskGb: 1024,
    disks: '2× 512 GB NVMe, software RAID (fixed)',
    bandwidth: '1 Gbps unmetered, guaranteed; no vRack',
    ddos: 'standard OVH anti-DDoS infrastructure; no Game firewall on this range',
    gameAwareDdos: false,
    stock: 'rbx, gra, bhs 1H-high; fra 1H-low; sbg, waw unavailable',
    inStock: true,
    source: `${OVH_EU_ECO} ; https://eco.ovhcloud.com/en-ie/`,
    notes:
      'Fixed configuration. 12-month upfront €740.89. The catalog gives RISE-S standard anti-DDoS only, not ' +
      'Game DDoS with a Minecraft Java profile. Sold by OVH US only for EU/CA DCs ($77).',
  },
  {
    ...OVH_DEDICATED,
    id: 'ovh-rise-m',
    product: 'RISE-M (Rise, 2025 Zen 5)',
    sku: '25risem01-v2',
    regions: 'fra, gra, rbx, waw, bhs, sbg',
    regionGroup: 'EU',
    currency: 'EUR',
    monthlyPrice: 99.99,
    hourlyPrice: null,
    setupFee: 99.99,
    ramGb: 64,
    cores: 12,
    threads: 24,
    cpuModel: 'AMD Ryzen 9 9900X (Zen 5), 4.4/5.6 GHz',
    st: passmark(4671, '6,774 samples'),
    localDiskGb: 1024,
    disks: '2× 512 GB NVMe, software RAID',
    bandwidth: '1 Gbps unmetered, guaranteed; 1 Gbps vRack',
    ddos: 'standard OVH anti-DDoS infrastructure',
    gameAwareDdos: false,
    stock: 'bhs, gra, rbx 1H-high (not fra)',
    inStock: true,
    source: OVH_EU_ECO,
    notes: '12-month upfront €1,139.89.',
  },
  {
    ...OVH_DEDICATED,
    id: 'ovh-rise-l',
    product: 'RISE-L (Rise, 2025 Zen 5)',
    sku: '25risel01-v1',
    regions: 'fra, gra, rbx, waw, bhs, sbg',
    regionGroup: 'EU',
    currency: 'EUR',
    monthlyPrice: 149.99,
    hourlyPrice: null,
    setupFee: 149.99,
    ramGb: 128,
    cores: 16,
    threads: 32,
    cpuModel: 'AMD Ryzen 9 9950X (Zen 5), 4.3/5.7 GHz',
    st: passmark(4728, '6,827 samples'),
    localDiskGb: 1920,
    disks: '2× 960 GB NVMe, software RAID',
    bandwidth: '1 Gbps unmetered, guaranteed; 1 Gbps vRack',
    ddos: 'standard OVH anti-DDoS infrastructure',
    gameAwareDdos: false,
    stock: 'rbx 1H-high only; bhs, fra, gra, sbg, waw unavailable',
    inStock: true,
    source: `${OVH_EU_ECO} ; https://eco.ovhcloud.com/en-ie/`,
    notes:
      '12-month upfront €1,709.89. Contradiction: cpu-performance.md says RISE-L is not on the Rise page (unverified); ' +
      'ovhcloud.md and regions.md find it in the catalog and on the eco storefront at €149.99.',
  },
  {
    ...OVH_DEDICATED,
    id: 'ovh-rise-game-2',
    product: 'RISE-GAME-2 (Eco game server)',
    sku: '24risegame022',
    regions: 'fra, gra, lon, sbg, waw, bhs',
    regionGroup: 'EU',
    currency: 'EUR',
    monthlyPrice: 89.99,
    hourlyPrice: null,
    setupFee: 89.99,
    ramGb: 64,
    ramOptions: [{ ramGb: 128, extraMonthly: 32 }],
    cores: 8,
    threads: 16,
    cpuModel: 'AMD Ryzen 7 5800X (Zen 3), 3.8/4.7 GHz',
    st: passmark(3448, '25,890 samples'),
    localDiskGb: 1920,
    disks: '2× 960 GB NVMe',
    bandwidth: '1 Gbps unmetered, guaranteed; no vRack',
    ddos: 'Game DDoS Protection (Minecraft Java/Query profiles, 30 rules per IP)',
    gameAwareDdos: true,
    stock: 'bhs, gra, lon, sbg, waw 1H; fra 1H-low/72H',
    inStock: true,
    source: OVH_EU_ECO,
    notes: '12-month upfront €1,025.89. Zen 3.',
  },
  {
    ...OVH_DEDICATED,
    id: 'ovh-game-1',
    product: 'GAME-1 2026 (Bare Metal Game)',
    sku: '26game01-v4',
    regions: 'bhs, gra, waw, fra',
    regionGroup: 'EU',
    currency: 'EUR',
    monthlyPrice: 279.99,
    hourlyPrice: null,
    setupFee: 279.99,
    ramGb: 64,
    ramOptions: OVH_RAM_GAME,
    cores: 8,
    threads: 16,
    cpuModel: 'AMD Ryzen 7 9800X3D (Zen 5, 3D V-Cache), 4.7/5.2 GHz',
    st: passmark(4420, '26,782 samples'),
    localDiskGb: 1920,
    disks: '2× 960 GB NVMe, software RAID',
    bandwidth: '1 Gbps unmetered; no vRack',
    ddos: 'Game DDoS Protection (Minecraft Java/Bedrock/Query, 100 rules per IP), always on, unmetered',
    gameAwareDdos: true,
    stock: 'bhs, fra, gra, waw: 1H',
    inStock: true,
    source: `${OVH_EU_BM} ; https://www.ovhcloud.com/en-ie/bare-metal/game/`,
    notes:
      '12-month upfront €3,191.89. Contradiction: the bare-metal catalog tags GAME 2026 `antiddos: standard` while the pages and ' +
      'guide say Game DDoS is included.',
  },
  {
    ...OVH_DEDICATED,
    id: 'ovh-game-2',
    product: 'GAME-2 2026 (Bare Metal Game)',
    sku: '26game02-v4',
    regions: 'bhs, gra, waw, fra',
    regionGroup: 'EU',
    currency: 'EUR',
    monthlyPrice: 313.99,
    hourlyPrice: null,
    setupFee: 313.99,
    ramGb: 64,
    ramOptions: OVH_RAM_GAME,
    cores: 16,
    threads: 32,
    cpuModel: 'AMD Ryzen 9 9950X3D (Zen 5, 3D V-Cache), 4.3/5.7 GHz',
    st: passmark(4737, '12,206 samples'),
    localDiskGb: 1920,
    disks: '2× 960 GB NVMe',
    bandwidth: '1 Gbps unmetered; no vRack',
    ddos: 'Game DDoS Protection (100 rules per IP), always on, unmetered',
    gameAwareDdos: true,
    stock: 'bhs, gra 1H; fra 1H-low/72H; waw 1H-low',
    inStock: true,
    source: `${OVH_EU_BM} ; https://www.ovhcloud.com/en-ie/bare-metal/game/`,
    notes: '12-month upfront €3,579.49. Same antiddos-tag contradiction and RAM-renewal risk as GAME-1.',
  },
  {
    ...OVH_DEDICATED,
    id: 'ovh-advance-2-2026',
    product: 'ADVANCE-2 2026 (Bare Metal Advance)',
    sku: '26adv02-v7',
    regions: 'bhs, fra, gra, lon, rbx, sbg, waw',
    regionGroup: 'EU',
    currency: 'EUR',
    monthlyPrice: 199.99,
    hourlyPrice: null,
    setupFee: 199.99,
    ramGb: 64,
    ramOptions: [
      { ramGb: 128, extraMonthly: 92 },
      { ramGb: 192, extraMonthly: 136 },
      { ramGb: 256, extraMonthly: 256 },
    ],
    cores: 8,
    threads: 16,
    cpuModel: 'AMD EPYC 4345P (Zen 5), 3.8/5.5 GHz',
    st: passmark(4408, '52 samples'),
    localDiskGb: 1920,
    disks: '2× 960 GB NVMe',
    bandwidth: '3 Gbps unmetered, guaranteed; 25 Gbps vRack',
    ddos: 'standard OVH anti-DDoS infrastructure',
    gameAwareDdos: false,
    stock: 'not checked for this plan code (ADVANCE-1 2026 was in stock in all seven EU/CA DCs)',
    inStock: null,
    source: `${OVH_EU_BM} ; https://www.ovhcloud.com/en-ie/bare-metal/advance/`,
    notes:
      '12-month upfront €2,279.89. SLA 99.95% (Advance). The eco catalog lists 2024 Advance codes ~22% cheaper; unverified as purchasable.',
  },
]

export const OVH_US_SERVERS: readonly Offering[] = [
  {
    ...OVH_DEDICATED,
    provider: 'OVHcloud US',
    id: 'ovh-us-rise-game-1',
    product: 'RISE-GAME-1 (US DC)',
    sku: '24risegame012-us',
    regions: 'vin (Vint Hill VA), hil (Hillsboro OR)',
    regionGroup: 'US',
    currency: 'USD',
    monthlyPrice: 90,
    hourlyPrice: null,
    setupFee: 90,
    ramGb: 32,
    ramOptions: [{ ramGb: 64, extraMonthly: 14 }],
    cores: 6,
    threads: 12,
    cpuModel: 'AMD Ryzen 5 5600X (Zen 3)',
    st: passmark(3366, '35,885 samples'),
    localDiskGb: 1024,
    disks: '2× 512 GB NVMe',
    bandwidth: '1 Gbps unmetered',
    ddos: 'Game DDoS per the EU catalog tag for RISE-GAME; not separately confirmed on the US catalog',
    gameAwareDdos: null,
    stock: 'hil, vin 1H',
    inStock: true,
    source: `${OVH_US_ECO} ; https://eco.us.ovhcloud.com/rise/`,
    notes: 'US account and legal entity separate from the EU one. 12-month upfront $1,026.',
  },
  {
    ...OVH_DEDICATED,
    provider: 'OVHcloud US',
    id: 'ovh-us-rise-game-2',
    product: 'RISE-GAME-2 (US DC)',
    sku: '24risegame022-v1-us',
    regions: 'vin, hil',
    regionGroup: 'US',
    currency: 'USD',
    monthlyPrice: 104,
    hourlyPrice: null,
    setupFee: 104,
    ramGb: 64,
    ramOptions: [{ ramGb: 128, extraMonthly: 28 }],
    cores: 8,
    threads: 16,
    cpuModel: 'AMD Ryzen 7 5800X (Zen 3)',
    st: passmark(3448, '25,890 samples'),
    localDiskGb: 1920,
    disks: '2× 960 GB NVMe',
    bandwidth: '1 Gbps unmetered',
    ddos: 'Game DDoS per the EU catalog tag for RISE-GAME; not separately confirmed on the US catalog',
    gameAwareDdos: null,
    stock: 'vin, hil in stock',
    inStock: true,
    source: OVH_US_ECO,
    notes: 'The cheapest 64 GB high-clock box in the US (regions.md), but Zen 3. 12-month upfront $1,185.60.',
  },
  {
    ...OVH_DEDICATED,
    provider: 'OVHcloud US',
    id: 'ovh-us-game-2',
    product: 'GAME-2 2026 (US DC)',
    sku: '26game02-v4-us',
    regions: 'vin, hil',
    regionGroup: 'US',
    currency: 'USD',
    monthlyPrice: 401,
    hourlyPrice: null,
    setupFee: 401,
    ramGb: 64,
    ramOptions: [
      { ramGb: 128, extraMonthly: 117 },
      { ramGb: 192, extraMonthly: 229 },
      { ramGb: 256, extraMonthly: 326 },
    ],
    cores: 16,
    threads: 32,
    cpuModel: 'AMD Ryzen 9 9950X3D (Zen 5, 3D V-Cache)',
    st: passmark(4737, '12,206 samples'),
    localDiskGb: 1920,
    disks: '2× 960 GB NVMe',
    bandwidth: '1 Gbps unmetered',
    ddos: 'Game DDoS protection included (US Game page)',
    gameAwareDdos: true,
    stock: 'vin in stock; hil 1H-high/72H',
    inStock: true,
    source: `${OVH_US_BM} ; https://us.ovhcloud.com/bare-metal/game/`,
    notes:
      'The US Game page says "Coming Soon" while the availability API shows stock. 12-month upfront $4,571.40.',
  },
]
