// SPDX-FileCopyrightText: 2026 The Cubepals Authors
//
// SPDX-License-Identifier: AGPL-3.0-only

/**
 * Dedicated servers from bare-metal specialists as catalog entries: phoenixNAP, Latitude.sh, Cherry Servers.
 * One entry each, with no shared constants; every field is written out in its entry.
 */
import { CHECKED, type Offering, passmark } from './offering.ts'

export const SPECIALIST_SERVERS: readonly Offering[] = [
  {
    id: 'phoenixnap-s3-c3-medium',
    provider: 'phoenixNAP',
    product: 'Bare Metal Cloud',
    sku: 's3.c3.medium',
    modelClass: 'C',
    regions: 'Ashburn, Chicago, Phoenix, Seattle, Amsterdam, Singapore (same price)',
    regionGroup: 'EU+US',
    currency: 'USD',
    monthlyPrice: 248.99,
    hourlyPrice: 0.47,
    setupFee: null,
    minTerm: '1-month reservation for this price; 12-month $158.35/month, 36-month $145.85/month',
    billing: 'hourly on demand, or monthly reservations',
    billedWhenOff: null,
    ramGb: 128,
    cores: 24,
    fastCores: 8,
    threads: 32,
    dedicatedCpu: true,
    cpuModel: 'Intel Core i9-14900K (8 P-cores up to 6 GHz + 16 E-cores)',
    st: passmark(4690, '13,690 samples; P-cores only'),
    localDiskGb: 4000,
    disks: '2× 2 TB NVMe',
    raid1: true,
    bandwidth: '15 TB/month free (5 TB in Singapore); $0.01/GB beyond',
    egressOveragePerTb: 10,
    ipv4Monthly: 2.04,
    ddos: 'not stated',
    gameAwareDdos: null,
    stock: 'listed on the instances page',
    inStock: true,
    checked: CHECKED,
    sourceNote: 'bare-metal-specialists.md (§1, SKU data)',
    source:
      'https://phoenixnap.com/wp-content/themes/bootscore-child/cache/api-data.json ; https://phoenixnap.com/bare-metal-cloud/instances',
    notes:
      'Setup fee not published (null; the model counts none). Raptor Lake Vmin-shift history: confirm microcode 0x12B+. ' +
      'Tax treatment not stated.',
  },
  {
    id: 'latitude-f4-metal-small',
    provider: 'Latitude.sh (Megaport)',
    product: 'Metal Gen 4',
    sku: 'f4.metal.small',
    modelClass: 'C',
    regions: 'stock: NYC, CHI, ASH, ASH2, LAX2, SJC2, LON2, FRA2, AMS, SGP, TOR, SYD2, SAO2, MEX2, BUE',
    regionGroup: 'EU+US',
    currency: 'USD',
    monthlyPrice: 398,
    hourlyPrice: 1.09,
    setupFee: 0,
    minTerm: 'reserved month, prepaid; yearly $3,343 ($278.58/month)',
    billing: 'hourly on demand (730 h basis) or reserved upfront',
    billedWhenOff: null,
    ramGb: 96,
    cores: 12,
    threads: 24,
    dedicatedCpu: true,
    cpuModel: 'AMD EPYC 4484PX (Zen 4, 3D V-Cache)',
    st: passmark(4119, '3 samples, High margin of error'),
    localDiskGb: 1920,
    disks: '2× 960 GB NVMe',
    raid1: true,
    bandwidth: '20 TB/month free, pooled per region; $0.01/GB beyond',
    egressOveragePerTb: 10,
    ipv4Monthly: 0,
    ddos: 'included ("7 Tbps"); the gaming page says up to 2 Tbps; null-routes ~2 h above capacity',
    gameAwareDdos: false,
    stock: 'in stock in 15 locations incl. FRA2, AMS, NYC, ASH',
    inStock: true,
    checked: CHECKED,
    sourceNote: 'bare-metal-specialists.md (§1, §4, SKU data); regions.md (§1)',
    source: 'https://www.latitude.sh/pricing ; https://www.latitude.sh/pricing/networking',
    notes:
      'Contradiction: bare-metal-specialists.md reads $1.09/h on demand from the plan JSON, regions.md $0.55/h from the page. ' +
      'Taxes included per the FAQ. Megaport GSA: "not resell or resupply the Service".',
  },
  {
    id: 'cherry-ryzen-7950x',
    provider: 'Cherry Servers',
    product: 'Dedicated bare metal',
    sku: 'AMD Ryzen 7950X',
    modelClass: 'C',
    regions: 'LT, US-Chicago, NL, SG, SE, DE',
    regionGroup: 'EU+US',
    currency: 'EUR',
    monthlyPrice: 199,
    hourlyPrice: 0.341,
    setupFee: 0,
    minTerm: 'none; quarterly −5%, semi-annual −10%, annual −15%',
    billing: 'hourly or monthly',
    billedWhenOff: null,
    ramGb: 128,
    cores: 16,
    threads: 32,
    dedicatedCpu: true,
    cpuModel: 'AMD Ryzen 9 7950X (Zen 4)',
    st: passmark(4252, '8,877 samples'),
    localDiskGb: 2000,
    disks: '2× 1 TB NVMe',
    raid1: true,
    bandwidth: '100 TB on a 3 Gbps port',
    egressOveragePerTb: null,
    ipv4Monthly: null,
    ddos: '"standard built-in DDoS protection"',
    gameAwareDdos: false,
    stock: 'ZERO units in every region at check time',
    inStock: false,
    checked: CHECKED,
    sourceNote: 'bare-metal-specialists.md (§1, SKU data)',
    source:
      'https://api.cherryservers.com/v1/plans ; https://www.cherryservers.com/pricing/dedicated-servers',
    notes: 'The cheapest 16-core Ryzen price found, but not orderable: the model never picks it. Excl. VAT.',
  },
]
