// SPDX-FileCopyrightText: 2026 The Cubepals Authors
//
// SPDX-License-Identifier: AGPL-3.0-only

/**
 * Every Vultr offering in the catalog, written on `VULTR_COMMON`.
 * Its VMs (one per Minecraft server) and its bare metal are two arrays, because each sits in a
 * different place in `CATALOG`.
 * Other providers live in their own files beside this one.
 */
import { CHECKED, type Offering, passmark, type SingleThread } from './offering.ts'

const VULTR_COMMON = {
  provider: 'Vultr',
  regionGroup: 'EU+US',
  currency: 'USD',
  setupFee: 0,
  minTerm: 'none',
  billedWhenOff: true,
  egressOveragePerTb: 10,
  ipv4Monthly: 0,
  ddos: 'optional DDoS Protection, $10 per instance-month for 10 Gbps of L3/L4 mitigation',
  gameAwareDdos: false,
  checked: CHECKED,
  sourceNote: 'vultr.md (§3–5, §7–8, SKU data)',
} as const
const VULTR_VOC_ST: SingleThread = {
  passmark: null,
  index: [41, 58],
  tag: '[Independent]',
  basis:
    'generation not pinned: guests observed on EPYC Rome and Milan (VPSBenchmarks); cpu-performance.md §6',
}
const VULTR_VM_BILLING =
  'hourly (1 h minimum) up to the monthly price; the support doc says a 672 h cap, the API implies 730 h'

export const VULTR_VMS: readonly Offering[] = [
  {
    ...VULTR_COMMON,
    id: 'vultr-voc-g-1c-4gb',
    product: 'Optimized Cloud Compute – General Purpose (dedicated vCPU)',
    sku: 'voc-g-1c-4gb-30s-amd',
    modelClass: 'A',
    regions: '33 regions incl. fra, ams, ewr, ord (São Paulo 1.5×)',
    monthlyPrice: 30,
    hourlyPrice: 0.041,
    billing: VULTR_VM_BILLING,
    ramGb: 4,
    cores: null,
    threads: 1,
    dedicatedCpu: true,
    cpuModel: 'AMD EPYC, generation not pinned (Rome and Milan observed)',
    st: VULTR_VOC_ST,
    localDiskGb: 30,
    disks: '30 GB local NVMe',
    raid1: false,
    bandwidth: '4 TB/month pooled account-wide, plus 2 TB free per account; $0.01/GB beyond',
    storageWhileOffGbMonth: 0.05,
    stock: 'in stock in 33 of 33 regions',
    inStock: true,
    source:
      'https://api.vultr.com/v2/plans?per_page=500 ; https://docs.vultr.com/support/platform/billing/how-am-i-billed-for-my-servers',
    notes:
      'A stopped instance bills in full until destroyed; keeping the world as a snapshot costs $0.05/GB-month. vCPU = one hardware thread. ' +
      'The ToS reportedly bars reselling "access to the Services" without written permission (page blocked).',
  },
  {
    ...VULTR_COMMON,
    id: 'vultr-voc-c-2c-4gb',
    product: 'Optimized Cloud Compute – CPU Optimized (dedicated vCPU)',
    sku: 'voc-c-2c-4gb-50s-amd',
    modelClass: 'A',
    regions: '32 regions incl. fra, ams, ewr, ord',
    monthlyPrice: 40,
    hourlyPrice: 0.055,
    billing: VULTR_VM_BILLING,
    ramGb: 4,
    cores: null,
    threads: 2,
    dedicatedCpu: true,
    cpuModel: 'AMD EPYC, generation not pinned (Rome and Milan observed)',
    st: VULTR_VOC_ST,
    localDiskGb: 50,
    disks: '50 GB local NVMe',
    raid1: false,
    bandwidth: '5 TB/month pooled, plus 2 TB free per account',
    storageWhileOffGbMonth: 0.05,
    stock: 'in stock in 32 of 33 regions',
    inStock: true,
    source: 'https://api.vultr.com/v2/plans?per_page=500',
    notes: 'Two dedicated threads, likely one physical core (cpu-performance.md §3).',
  },
  {
    ...VULTR_COMMON,
    id: 'vultr-voc-c-4c-8gb',
    product: 'Optimized Cloud Compute – CPU Optimized (dedicated vCPU)',
    sku: 'voc-c-4c-8gb-75s-amd',
    modelClass: 'A',
    regions: '32 regions incl. fra, ams, ewr, ord',
    monthlyPrice: 80,
    hourlyPrice: 0.11,
    billing: VULTR_VM_BILLING,
    ramGb: 8,
    cores: null,
    threads: 4,
    dedicatedCpu: true,
    cpuModel: 'AMD EPYC, generation not pinned (Rome and Milan observed)',
    st: VULTR_VOC_ST,
    localDiskGb: 75,
    disks: '75 GB local NVMe',
    raid1: false,
    bandwidth: '6 TB/month pooled, plus 2 TB free per account',
    storageWhileOffGbMonth: 0.05,
    stock: 'in stock in 32 of 33 regions',
    inStock: true,
    source: 'https://api.vultr.com/v2/plans?per_page=500',
    notes: 'The like-for-like dedicated VM for Blockly 8 GB (4 vCPU, as Fly performance-4x).',
  },
  {
    ...VULTR_COMMON,
    id: 'vultr-vx1-g-2c-8g',
    product: 'VX1 Cloud Compute – General Purpose (dedicated vCPU)',
    sku: 'vx1-g-2c-8g',
    modelClass: 'A',
    regions: 'ams, atl, ewr, lhr, mxp, nrt, ord, sea, syd (not fra)',
    monthlyPrice: 43.8,
    hourlyPrice: 0.06,
    billing: 'hourly with NO monthly cap (actual hours in the month)',
    ramGb: 8,
    cores: null,
    threads: 2,
    dedicatedCpu: true,
    cpuModel: 'AMD EPYC "Turin" (guest CPU string; exact SKU unpublished), ~2.4 GHz',
    st: {
      passmark: null,
      index: 78,
      tag: '[Independent]',
      basis:
        'one Geekbench 6 SC run of 2,661 (VPSBenchmarks, Jun 2026) ÷ 9950X 3,410; not PassMark (vultr.md §4)',
    },
    localDiskGb: null,
    disks: 'none: boots from NVMe block storage at $0.10/GB-month, which survives deleting the VM',
    raid1: false,
    bandwidth: '5 TB/month pooled, plus 2 TB free per account',
    storageWhileOffGbMonth: 0.1,
    stock: 'in stock in 9 of 33 regions',
    inStock: true,
    source: 'https://api.vultr.com/v2/plans?per_page=500 ; https://docs.vultr.com/vultr-vx1-cloud-compute',
    notes:
      'Deleting the VM and keeping the block boot volume is the only way to stop paying compute on Vultr. Vultr positions VX1 ' +
      'for workloads "where single-core speed … [is] less important", yet independent single-core results are high.',
  },
]

export const VULTR_SERVERS: readonly Offering[] = [
  {
    ...VULTR_COMMON,
    id: 'vultr-bm-4245p',
    product: 'Bare Metal',
    sku: 'vbm-6c-32gb-amd',
    modelClass: 'C',
    regions: 'stock: atl, cdg, dfw, ewr, fra, itm, jnb, lax, lhr, man, ord, scl, sgp, sjc, syd',
    monthlyPrice: 295,
    hourlyPrice: 0.41,
    billing: 'hourly (1 h minimum) up to the monthly price',
    ramGb: 32,
    cores: 6,
    threads: 12,
    dedicatedCpu: true,
    cpuModel: 'AMD EPYC 4245P (Zen 5)',
    st: passmark(4575, '45 samples'),
    localDiskGb: 1920,
    disks: '2× 960 GB NVMe',
    raid1: true,
    bandwidth: '10 TB/month pooled account-wide; $0.01/GB beyond',
    ddos: 'whether the $10 DDoS add-on covers bare metal is unverified',
    stock: 'in stock in 15 regions, EU and US',
    inStock: true,
    source: 'https://api.vultr.com/v2/plans-metal?per_page=500',
    notes: 'No snapshots or block storage on bare metal. No setup fee; hourly exit.',
  },
  {
    ...VULTR_COMMON,
    id: 'vultr-bm-4345p',
    product: 'Bare Metal',
    sku: 'vbm-8c-64gb-amd',
    modelClass: 'C',
    regions: 'stock: ams, dfw, fra, itm, jnb, lhr, man, mel, mia, ord, sgp',
    monthlyPrice: 365,
    hourlyPrice: 0.55,
    billing: 'hourly (1 h minimum) up to the monthly price',
    ramGb: 64,
    cores: 8,
    threads: 16,
    dedicatedCpu: true,
    cpuModel: 'AMD EPYC 4345P (Zen 5)',
    st: passmark(4408, '52 samples'),
    localDiskGb: 3890,
    disks: '2× 1,945 GB NVMe',
    raid1: true,
    bandwidth: '10 TB/month pooled account-wide; $0.01/GB beyond',
    ddos: 'whether the $10 DDoS add-on covers bare metal is unverified',
    stock: 'in stock in 11 regions (fra, ams, lhr; dfw, ord, mia)',
    inStock: true,
    source: 'https://api.vultr.com/v2/plans-metal?per_page=500',
    notes:
      'Contradiction: the API hourly rate × 730 = $401.50 against the $365 monthly price; the hourly rate is unverified.',
  },
  {
    ...VULTR_COMMON,
    id: 'vultr-bm-7443p',
    product: 'Bare Metal',
    sku: 'vbm-24c-256gb-amd',
    modelClass: 'C',
    regions: 'stock: ams, blr, cdg, itm, jnb, lax, lhr, mad, nrt',
    monthlyPrice: 725,
    hourlyPrice: 0.993,
    billing: 'hourly (1 h minimum) up to the monthly price',
    ramGb: 256,
    cores: 24,
    threads: 48,
    dedicatedCpu: true,
    cpuModel: 'AMD EPYC 7443P (Zen 3 server, 2.85 GHz)',
    st: passmark(2898, '90 samples'),
    localDiskGb: 960,
    disks: '2× 480 GB SSD (SATA class, small for 256 GB of servers)',
    raid1: true,
    bandwidth: '10 TB/month pooled account-wide; $0.01/GB beyond',
    ddos: 'whether the $10 DDoS add-on covers bare metal is unverified',
    stock: 'in stock in 9 regions (ams, lhr, cdg, mad; lax)',
    inStock: true,
    source: 'https://api.vultr.com/v2/plans-metal?per_page=500',
    notes: 'Many cores at a low single-thread index; disks too small for a full 256 GB node of worlds.',
  },
]
